### ISSUE TITLE
size of elements

### ISSUE THREAD

**Issue by Lashaka** [Lashaka/Fun-Camera#13]
for example the off white rectangle behind the camera screens

**Comment by lashaka** [comment]
@ChariBasaur  , in order to apply once application to different screen sizes i've implemented a function that changes element sizes according to window size, it cannot be perfect to every 1x1 pixel, so i've made it work globally to 4  different 'Extreme Situations' , obviously some look better and some worse, if any of them look critially bad open an issue.

here how it looks:

## 1500x800 Default screen
![default](https://user-images.githubusercontent.com/69360460/211795757-ce07c82f-2d2c-4146-8994-10b0c26080ac.png)

## MAX 1920X1080 Enlarged screen
![enlarged screen1](https://user-images.githubusercontent.com/69360460/211794764-1e078ca7-37e8-459f-ab21-29692eb4fb57.png)

## MIN 1350X800 minimum screen
![small screen 1](https://user-images.githubusercontent.com/69360460/211796155-5db6d12a-a0b3-4249-ab76-afa810c1ad3b.png)


## Y Long screen 
![long screen 1](https://user-images.githubusercontent.com/69360460/211794771-9c5b068a-f58c-474b-a9b1-4dc39bca0dab.png)


## X Wide screen
![wide screen 1](https://user-images.githubusercontent.com/69360460/211794777-ac268948-634b-4f6b-b446-319ccb6a1eba.png)
